<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:msxsl="urn:schemas-microsoft-com:xslt" exclude-result-prefixes="msxsl"
>
    <xsl:output method="xml" indent="yes"/>

  <xsl:template match="/">
          <html>
            <head>
              
            </head>
            <body>
            <xsl:apply-templates select="@* | node()"/>
            </body>
          </html>
     
    </xsl:template>

  <xsl:template match="sbplanet">
    <tr>
    <xsl:for-each select="./*">
      <td>
        <xsl:value-of select="."/>
      </td>
    </xsl:for-each>
    </tr>
  </xsl:template>

    <xsl:template match="NewDataSet">
    <table>
      <thead>
        <tr>
          <xsl:for-each select="sbplanet[1]/*">
            <td>
              <xsl:value-of select="local-name()"/>
            </td>
          </xsl:for-each>
        </tr>
      </thead>
      <tbody>
        <xsl:apply-templates />
      </tbody>
    </table>
      Generated by the <a href="https://github.com/showmethebitcoin/Starbound-Planet-Scanner"> Starbound Planet Scanner </a>
  </xsl:template>
  
</xsl:stylesheet>
